# Deploy docker-compose with inline v2 compose

- name: Create a network msnet
  docker_network:
    name: msnet

- docker_compose:
    project_src: "{{ project_folder }}"
    state: absent

- docker_compose:
    project_name: lab7ms
    definition:
      version: '2'
      services:
        servlets:
          build: "{{ project_folder }}"
          expose:
            - "8080"
          ports:
            - "8080:8080"
          networks:
            - msnet
          restart: always
  register: output

- assert:
    that:
      - "servlets.lab7ms_servlets_1.state.running"