---
- name: Create project directory
  file:
    path: "{{ project_folder }}"
    state: directory
    mode: 0755

- name: Copy project Dockerfile
  copy:
   src: Dockerfile
   dest: "{{ project_folder }}"