- name: 1
    - docker_compose:
        project_src: "{{ project_folder }}"
        state: absent

- name: 2
    - docker_compose:
        project_name: "{{ project_name }}"
        definition:
          version: '2'
          services:
            servlets:
              build: "{{ project_folder }}"
              expose:
                - "8080"
              ports:
                - "8080:8080"
          restart: always
    register: output

- name: 3
  - assert:
      that:
        - "{{ service_name }}.{{ project_name }}_{{ service_name }}_1.state.running"