---
- name: Create project directory
  file:
    path: "{{ project_folder }}"
    state: directory
    mode: 0755

- name: Copy project file
  copy:
   src: "{{ item }}"
   dest: "{{ project_folder }}"
  with_items: "{{ docker_files | join(', ') }}"
  register: copy_res