- name: Install {{ _docker_packages | join(', ') }}
  package:
    pkg: {{ _docker_package }}
      state: present
      update_cache: yes

- name: Ensure docker service is started
  systemd:
    name: docker
    state: started

- name: Install pip from repo
  package:
    state: latest
    name: python3-pip

- name: Install {{ _python_packages | join(', ') }} packages with pip
    pip:
    name: "{{ _python_package_ }}"