- name: Install {{ _docker_packages | join(', ') }}
  package:
    name: "{{ _docker_packages }}"
    state: latest
    update_cache: yes

- name: Ensure docker service is started
  systemd:
    name: docker
    state: started

- name: Install {{ _python_packages | join(', ') }} packages with pip
  pip:
    name: "{{ _python_packages }}"